# Generated by Django 5.2.17 on 2026-09-02 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                (
                    "isin",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                (
                    "exchange",
                    models.CharField(
                        choices=[("NSE", "NSE"), ("BSE", "BSE")],
                        default="NSE",
                        max_length=4,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("lot_size", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["symbol"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("symbol", "exchange"), name="uniq_symbol_exchange"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CorporateAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SPLIT", "SPLIT"),
                            ("BONUS", "BONUS"),
                            ("SYMBOL_CHANGE", "SYMBOL_CHANGE"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ex_date", models.DateField()),
                (
                    "ratio_from",
                    models.DecimalField(decimal_places=6, default=1, max_digits=12),
                ),
                (
                    "ratio_to",
                    models.DecimalField(decimal_places=6, default=1, max_digits=12),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporate_actions",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["ex_date"],
            },
        ),
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=4, max_digits=18)),
                ("as_of", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(default="MANUAL", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "stock"), name="uniq_user_stock_price"
                    )
                ],
            },
        ),
    ]
