# Generated by Django 5.2.17 on 2026-09-02 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0001_initial"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "cost_basis",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "average_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "realized_pnl_fifo",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "total_charges_paid",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "dividends",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "break_even",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "recovery_break_even",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("ledger_hash", models.CharField(blank=True, max_length=32)),
                ("last_rebuilt_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="transactions.portfolio",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="stocks.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["stock__symbol"],
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_qty", models.DecimalField(decimal_places=6, max_digits=18)),
                ("remaining_qty", models.DecimalField(decimal_places=6, max_digits=18)),
                ("buy_price", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "buy_charges",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "cost_per_share",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "break_even",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("acquisition_date", models.DateField()),
                (
                    "source_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="portfolio.position",
                    ),
                ),
            ],
            options={
                "ordering": ["acquisition_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="SellAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qty", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "fifo_cost_basis",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "fifo_realized_pnl",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "wac_cost_basis",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "wac_realized_pnl",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("holding_days", models.IntegerField(default=0)),
                (
                    "term",
                    models.CharField(
                        choices=[("SHORT", "SHORT"), ("LONG", "LONG")], max_length=8
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="portfolio.lot",
                    ),
                ),
                (
                    "sell_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "stock"), name="uniq_portfolio_stock_position"
            ),
        ),
    ]
