# Generated by Django 5.2.17 on 2026-09-02 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker", models.CharField(max_length=40)),
                ("plan", models.CharField(max_length=40)),
                ("display_name", models.CharField(max_length=120)),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("EQUITY_DELIVERY", "EQUITY_DELIVERY"),
                            ("EQUITY_INTRADAY", "EQUITY_INTRADAY"),
                            ("FUTURES", "FUTURES"),
                            ("OPTIONS", "OPTIONS"),
                        ],
                        default="EQUITY_DELIVERY",
                        max_length=24,
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[("NSE", "NSE"), ("BSE", "BSE")],
                        default="NSE",
                        max_length=4,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("components", models.JSONField(default=list)),
                ("is_system", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["broker", "plan", "exchange"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "broker",
                            "plan",
                            "segment",
                            "exchange",
                            "effective_from",
                        ),
                        name="uniq_plan_version",
                    )
                ],
            },
        ),
    ]
