# Generated by Django 5.2.17 on 2026-09-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokerplan",
            name="verified",
            field=models.BooleanField(
                default=False, help_text="Checked against a real broker bill."
            ),
        ),
    ]
