# Generated by Django 5.2.17 on 2026-09-02 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("charges", "0001_initial"),
        ("stocks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default", max_length=80)),
                ("is_default", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BUY", "BUY"),
                            ("SELL", "SELL"),
                            ("OPENING_BALANCE", "OPENING_BALANCE"),
                            ("DIVIDEND", "DIVIDEND"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("price", models.DecimalField(decimal_places=4, max_digits=18)),
                ("trade_date", models.DateField()),
                ("sequence_no", models.IntegerField(default=0)),
                (
                    "exchange",
                    models.CharField(
                        choices=[("NSE", "NSE"), ("BSE", "BSE")],
                        default="NSE",
                        max_length=4,
                    ),
                ),
                ("charge_breakdown", models.JSONField(blank=True, default=dict)),
                (
                    "total_charges",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "charge_override",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("SUPERSEDED", "SUPERSEDED")],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broker_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="charges.brokerplan",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="transactions.portfolio",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="stocks.stock",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-trade_date", "-sequence_no", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "stock", "trade_date", "sequence_no"],
                        name="transaction_user_id_89eea3_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="transaction_user_id_9cef77_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("user", "idempotency_key"),
                        name="uniq_user_idempotency_key",
                    )
                ],
            },
        ),
    ]
